#!/usr/bin/env bash
set -euo pipefail

# Bootstrap a machine from Azure Key Vault after Azure CLI login.
# Creates a local env file with non-secret Key Vault metadata and installs a
# convenient global wrapper at ~/.local/bin/copilot-azurebrains.

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
if [[ -z "${ENV_FILE:-}" && ! -f "$ROOT_DIR/.env" && -f "$ROOT_DIR/private/.env" ]]; then
  ENV_FILE="$ROOT_DIR/private/.env"
else
  ENV_FILE="${ENV_FILE:-$ROOT_DIR/.env}"
fi
CONFIG_FILE="${AZUREBRAINS_CONFIG_FILE:-$HOME/.config/azurebrains/copilot-azurebrains.env}"
WRAPPER_FILE="${AZUREBRAINS_WRAPPER_FILE:-$HOME/.local/bin/copilot-azurebrains}"

if [[ -f "$ENV_FILE" ]]; then
  # shellcheck disable=SC1090
  set -a
  source "$ENV_FILE"
  set +a
fi

AZURE_KEYVAULT_NAME="${AZURE_KEYVAULT_NAME:-}"
AZURE_KEYVAULT_CONFIG_SECRET_NAME="${AZURE_KEYVAULT_CONFIG_SECRET_NAME:-copilot-azure-config}"

if [[ -z "$AZURE_KEYVAULT_NAME" ]]; then
  echo "ERROR: AZURE_KEYVAULT_NAME is required" >&2
  exit 2
fi

if ! command -v az >/dev/null 2>&1; then
  echo "ERROR: Azure CLI is required. Install it and run az login." >&2
  exit 2
fi

if ! az account show >/dev/null 2>&1; then
  echo "Azure CLI is not logged in. Starting az login..." >&2
  az login >/dev/null
fi

if [[ -n "${AZURE_SUBSCRIPTION_ID:-}" ]]; then
  az account set --subscription "$AZURE_SUBSCRIPTION_ID"
fi

az_args=(keyvault secret show --vault-name "$AZURE_KEYVAULT_NAME" --name "$AZURE_KEYVAULT_CONFIG_SECRET_NAME" --query value -o tsv)
if [[ -n "${AZURE_SUBSCRIPTION_ID:-}" ]]; then
  az_args+=(--subscription "$AZURE_SUBSCRIPTION_ID")
fi

config_json="$(az "${az_args[@]}")"

mkdir -p "$(dirname "$CONFIG_FILE")" "$(dirname "$WRAPPER_FILE")"
chmod 700 "$(dirname "$CONFIG_FILE")"

{
  cat <<EOF
# Generated by scripts/install-from-keyvault.sh.
# No API key is stored here; the wrapper reads it from Azure Key Vault at runtime.
AZURE_KEYVAULT_NAME=$AZURE_KEYVAULT_NAME
AZURE_KEYVAULT_CONFIG_SECRET_NAME=$AZURE_KEYVAULT_CONFIG_SECRET_NAME
AZURE_SUBSCRIPTION_ID=${AZURE_SUBSCRIPTION_ID:-}
EOF
  CONFIG_JSON="$config_json" python3 - <<'PY'
import json
import os
import shlex

allowed_keys = {
    "AZURE_OPENAI_BASE_URL",
    "AZURE_OPENAI_MODEL",
    "AZURE_OPENAI_MAX_COMPLETION_TOKENS",
    "AZURE_KEYVAULT_SECRET_NAME",
    "COPILOT_PROVIDER_MODEL_ID",
    "COPILOT_PROVIDER_WIRE_API",
    "COPILOT_PROVIDER_MAX_PROMPT_TOKENS",
    "COPILOT_PROVIDER_MAX_OUTPUT_TOKENS",
    "COPILOT_MODEL",
    "COPILOT_CONTEXT_TIER",
    "COPILOT_REASONING_EFFORT",
    "COPILOT_SUBAGENT_EFFORT_LEVEL",
    "COPILOT_SUBAGENT_CONTEXT_TIER",
}

data = json.loads(os.environ["CONFIG_JSON"])
if not isinstance(data, dict):
    raise SystemExit("Key Vault configuration secret must contain a JSON object")

for key in sorted(allowed_keys):
    value = data.get(key)
    if value is None or value == "":
        continue
    print(f"{key}={shlex.quote(str(value))}")
PY
} > "$CONFIG_FILE"
chmod 600 "$CONFIG_FILE"

cat > "$WRAPPER_FILE" <<EOF
#!/usr/bin/env bash
set -euo pipefail

export ENV_FILE="\${AZUREBRAINS_CONFIG_FILE:-$CONFIG_FILE}"
exec "$ROOT_DIR/examples/copilot-azure-wrapper.sh" "\$@"
EOF
chmod 700 "$WRAPPER_FILE"

cat <<EOF
Installed portable Copilot Azure wrapper.

Config file: $CONFIG_FILE
Wrapper: $WRAPPER_FILE

Try:
  $WRAPPER_FILE --print-config
  $WRAPPER_FILE
EOF